
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/navbar/Footer";
import TextProvider from "./components/context/TextContext";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  const value = 'akash'

 
  return (
    <html lang="en">
      
      <body className="min-h-full flex flex-col">
  
       <TextProvider>
         <Navbar></Navbar>
          {children}
       </TextProvider>
         
        <Footer></Footer>
        </body>
      

    </html>
  );
}
