import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/navbar/Footer";
import TextProvider from "./components/context/TextContext";
import { ToastContainer } from "react-toastify";
import CountProvider from "./components/context/CountContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className="min-h-full flex flex-col">
        <CountProvider>
          <TextProvider>
            <Navbar></Navbar>

            <div className="mx-4 md:mx-20 lg:mx-30">{children}</div>
          </TextProvider>
        </CountProvider>
        <ToastContainer position="top-center"></ToastContainer>

        <Footer></Footer>
      </body>
    </html>
  );
}
